export const INVOICE_STATUSES = ['DRAFT', 'ISSUED', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED'] as const;
export const PAYMENT_METHODS = ['CASH', 'BANK_TRANSFER', 'UPI', 'CARD', 'CHEQUE', 'OTHER'] as const;

export type InvoiceStatus = (typeof INVOICE_STATUSES)[number];
export type PaymentMethod = (typeof PAYMENT_METHODS)[number];

export const BILLING_AUDIT_EVENTS = {
  INVOICE_CREATED: 'INVOICE_CREATED',
  INVOICE_UPDATED: 'INVOICE_UPDATED',
  INVOICE_ISSUED: 'INVOICE_ISSUED',
  INVOICE_CANCELLED: 'INVOICE_CANCELLED',
  INVOICE_LINE_ADDED: 'INVOICE_LINE_ADDED',
  INVOICE_LINE_REMOVED: 'INVOICE_LINE_REMOVED',
  PAYMENT_RECORDED: 'PAYMENT_RECORDED',
  INVOICE_PARTIALLY_PAID: 'INVOICE_PARTIALLY_PAID',
  INVOICE_PAID: 'INVOICE_PAID',
} as const;
